eye3_control:
    resource: "@Eye3ControlBundle/Controller"
    type:     annotation
    prefix:   /

login:
    path:     /login
    defaults: { _controller: Eye3ControlBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

home_page:
    path: /
    defaults: { _controller: Eye3ControlBundle:Default:index }

no_disponible:
    path: /desactivado
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'Eye3ControlBundle:Reporte:index.html.twig'
        maxAge:       86400
        sharedAge:    86400
