parameters:
#    eye3_control.example.class: Eye3\ControlBundle\Example

services:
#    eye3_control.example:
#        class: %eye3_control.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
